[menu]
executable = 'fuzzel'
args = [
     '--dmenu',
     '--no-exit-on-keyboard-focus-loss',
     '--width=60',
]

[format]
window_format = "{app_name:{:<10.10}} {title:{:<38.38}...} [{workspace_name:{:<1.2}}]\u0000icon\u001f{app_icon}"
workspace_format = "    Workspace {name} on output {output_name}:"
icon_dirs = [
    '/usr/share/icons/Tela-circle-nord/scalable/apps',
    '/usr/share/icons/hicolor/48x48/apps',
    '/usr/share/icons/hicolor/256x256/apps',
    '/usr/share/icons/hicolor/scalable/apps',
    '~/.local/share/icons/hicolor/48x48/apps/',
	'/var/lib/flatpak/exports/share/icons/hicolor/',
	'~/.local/share/flatpak/exports/share/icons/hicolor/',
	'/usr/share/icons'
]
